import os
import json
import configparser
import re
from google import genai
from google.genai import types
from dotenv import load_dotenv


def extract_content_with_gemini(file_path):
    """Uses Gemini to extract structured content from the slider buddy file as JSON."""
    load_dotenv()
    client = genai.Client()
    
    if not os.path.exists(file_path):
        print(f"Error: File not found at {file_path}")
        return []
        
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    prompt = f"""
    Read the following slide content generated by 'Slider Buddy'.
    Extract the content for each slide.
    Return the result ONLY as a JSON list of objects, where each object has:
    'slide': integer (slide number)
    'headline': string
    'subtitle': string (optional)
    'bullets': list of strings (optional)
    'takeaway': string (optional)
    
    Content:
    {content}
    """
    
    print("Extracting structured content using Gemini...")
    response = client.models.generate_content(
        model='gemini-3-flash-preview',
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
        )
    )
    
    try:
        return json.loads(response.text)
    except Exception as e:
        print(f"Error parsing JSON from Gemini: {e}")
        print(response.text)
        return []



def create_html(content_list, images_dir, output_path, brand_name):
    """Creates a clean, static HTML presentation with a warm theme."""
    html_content = f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apresentação Estratégica - {brand_name}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background-color: #fcf8f2; /* Warm cream */
            color: #2c241d; /* Dark brown/charcoal */
            margin: 0;
            padding: 40px;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
        }}
        header {{
            text-align: center;
            margin-bottom: 60px;
        }}
        h1 {{
            color: #8c6d53; /* Muted brown */
            font-size: 2.8rem;
            margin-bottom: 10px;
        }}
        .slide-card {{
            background-color: #ffffff;
            border: 1px solid #e8e0d5;
            border-radius: 12px;
            padding: 40px;
            margin-bottom: 40px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.05);
        }}
        h2 {{
            color: #d97724; /* Warm orange accent */
            font-size: 1.8rem;
            margin-top: 0;
            border-bottom: 2px solid #f7efe5;
            padding-bottom: 10px;
        }}
        ul {{
            list-style-type: none;
            padding: 0;
        }}
        li {{
            margin-bottom: 15px;
            font-size: 1.1rem;
            color: #4a3e35;
            padding-left: 25px;
            position: relative;
        }}
        li::before {{
            content: "★";
            color: #d97724;
            position: absolute;
            left: 0;
            font-size: 0.9rem;
            top: 3px;
        }}
        .takeaway {{
            margin-top: 25px;
            padding: 20px;
            background-color: #f7efe5;
            border-left: 4px solid #d97724;
            border-radius: 0 4px 4px 0;
            font-weight: bold;
            color: #2c241d;
            font-size: 1rem;
        }}
        .slide-image {{
            text-align: center;
            margin-top: 30px;
        }}
        .slide-image img {{
            max-width: 100%;
            border-radius: 8px;
            border: 1px solid #e8e0d5;
        }}
        .footer-links {{
            text-align: center;
            margin-top: 40px;
            font-size: 0.9rem;
            color: #8c6d53;
        }}
        .footer-links a {{
            color: #d97724;
            text-decoration: none;
            font-weight: bold;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Apresentação Estratégica</h1>
            <p style="color: #8c6d53; font-size: 1.2rem;">Foco no Tema: {brand_name}</p>
        </header>
    """
    
    for item in content_list:
        slide_num = item.get('slide')
        headline = item.get('headline', '')
        bullets = item.get('bullets', [])
        takeaway = item.get('takeaway', '')
        
        image_path = os.path.join("presentation/images", f"slide_{slide_num}_asset.png")
        
        html_content += f"""
        <div class="slide-card">
            <h2>{headline}</h2>
            <ul>
        """
        
        for bullet in bullets:
            html_content += f"<li>{bullet}</li>"
            
        html_content += """
            </ul>
        """
        
        if takeaway:
            html_content += f"""
            <div class="takeaway">Diretriz: {takeaway}</div>
            """
            
        html_content += f"""
            <div class="slide-image">
                <img src="{image_path}" alt="Visual do Slide {slide_num}">
            </div>
        </div>
        """
        
    html_content += """
        <div class="footer-links">
            <p>Gerado automaticamente via Gemini API | <a href="#" onclick="window.print();return false;">Salvar como PDF (Imprimir)</a></p>
        </div>
    </div>
</body>
</html>
    """
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    print(f"SUCCESS: Saved static HTML to {output_path}")

def main():
    # Read config to get brand name
    load_dotenv()
    config = configparser.ConfigParser()
    config.read('config.ini')
    brand_name = config.get('Crawler', 'search_terms')
    safe_brand_name = re.sub(r'\W+', '', brand_name.replace(' ', '_'))
    
    content_file = os.path.join("outputs", safe_brand_name, "presentation", "slider_buddy_content.txt")
    images_dir = os.path.join("outputs", safe_brand_name, "presentation", "images")
    
    # Outputs directly in the brand folder so they show up in Streamlit
    html_output = os.path.join("outputs", safe_brand_name, f"{safe_brand_name}_presentation.html")
    
    content_list = extract_content_with_gemini(content_file)
    
    if not content_list:
        print("No content to assemble.")
        return
    create_html(content_list, images_dir, html_output, safe_brand_name)

if __name__ == "__main__":
    main()
